<?php

namespace Database\Seeders;

use App\Models\QLearningState;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QLearningSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $data = [
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Kardio',
                'tujuan_workout' => 'Menurunkan Berat Badan',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Bagus',
                'workout_id' => 1,
                'q_value' => 0.8,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Obesitas',
                'kondisi_kesehatan' => 'Obesitas',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Menurunkan Berat Badan',
                'durasi_latihan' => 20,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Buruk',
                'workout_id' => 27, // Stretching
                'q_value' => 0.9,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan kurang',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'Kekuatan',
                'tujuan_workout' => 'Meningkatkan Massa Otot & Kekuatan',
                'durasi_latihan' => 40,
                'kelengkapan_alat' => 'Lengkap',
                'mood' => 'Bagus',
                'workout_id' => 38, // Bench Press
                'q_value' => 0.75,
            ],
            [
                'usia' => 'Lansia',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan berlebih',
                'kondisi_kesehatan' => 'Hipertensi',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 28, // Yoga 30 menit
                'q_value' => 0.82,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Cedera',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 20,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 27, // Stretching
                'q_value' => 0.85,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'HIIT',
                'tujuan_workout' => 'Meningkatkan Kebugaran Kardiovaskular',
                'durasi_latihan' => 25,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Bagus',
                'workout_id' => 35, // HIIT 20 menit
                'q_value' => 0.9,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan berlebih',
                'kondisi_kesehatan' => 'Diabetes',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Bodyweight Training',
                'tujuan_workout' => 'Meningkatkan Massa Otot & Kekuatan',
                'durasi_latihan' => 15,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Bagus',
                'workout_id' => 15, // Push-up 3 set
                'q_value' => 0.83,
            ],
            [
                'usia' => 'Lansia',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Obesitas',
                'kondisi_kesehatan' => 'Asma',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Kardio',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 4, // Jalan santai 30 menit
                'q_value' => 0.88,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan kurang',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Dance Fitness',
                'tujuan_workout' => 'Meningkatkan Kebugaran Kardiovaskular',
                'durasi_latihan' => 45,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Bagus',
                'workout_id' => 33, // Zumba
                'q_value' => 0.77,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'Dance Fitness',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 45,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Bagus',
                'workout_id' => 34, // Aerobik 45 menit
                'q_value' => 0.79,
            ],
            [
                'usia' => 'Lansia',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan kurang',
                'kondisi_kesehatan' => 'Hipotensi',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Kardio',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 20,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 4, // Jalan santai 30 menit
                'q_value' => 0.86,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan berlebih',
                'kondisi_kesehatan' => 'Hipertensi',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 28, // Yoga 30 menit
                'q_value' => 0.84,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Obesitas',
                'kondisi_kesehatan' => 'Obesitas',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Bodyweight Training',
                'tujuan_workout' => 'Menurunkan Berat Badan',
                'durasi_latihan' => 15,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Buruk',
                'workout_id' => 16, // Push-up 5 set
                'q_value' => 0.76,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'HIIT',
                'tujuan_workout' => 'Meningkatkan Kebugaran Kardiovaskular',
                'durasi_latihan' => 25,
                'kelengkapan_alat' => 'Lengkap',
                'mood' => 'Bagus',
                'workout_id' => 37, // Cardio Boxing
                'q_value' => 0.81,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan kurang',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Dance Fitness',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 40,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Bagus',
                'workout_id' => 33, // Zumba
                'q_value' => 0.74,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'Bodyweight Training',
                'tujuan_workout' => 'Meningkatkan Massa Otot & Kekuatan',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Bagus',
                'workout_id' => 26, // Bodyweight Circuit
                'q_value' => 0.78,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Penyakit Jantung',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 15,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Buruk',
                'workout_id' => 27, // Stretching
                'q_value' => 0.82,
            ],
            [
                'usia' => 'Lansia',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan berlebih',
                'kondisi_kesehatan' => 'Asma',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Kardio',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 13, // Bersepeda Statis
                'q_value' => 0.86,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'HIIT',
                'tujuan_workout' => 'Meningkatkan Kebugaran Kardiovaskular',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Bagus',
                'workout_id' => 35, // HIIT 20 menit
                'q_value' => 0.85,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan kurang',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Meningkatkan Fleksibilitas',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Bagus',
                'workout_id' => 29, // Power Yoga 30 menit
                'q_value' => 0.8,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan berlebih',
                'kondisi_kesehatan' => 'Diabetes',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Bodyweight Training',
                'tujuan_workout' => 'Menurunkan Berat Badan',
                'durasi_latihan' => 20,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Buruk',
                'workout_id' => 15, // Push-up 3 set
                'q_value' => 0.75,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'Kekuatan',
                'tujuan_workout' => 'Meningkatkan Massa Otot & Kekuatan',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Lengkap',
                'mood' => 'Bagus',
                'workout_id' => 39, // Bench Press
                'q_value' => 0.87,
            ],
            [
                'usia' => 'Lansia',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Asma',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 31, // Tai Chi
                'q_value' => 0.85,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan berlebih',
                'kondisi_kesehatan' => 'Obesitas',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Kardio',
                'tujuan_workout' => 'Menurunkan Berat Badan',
                'durasi_latihan' => 45,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Bagus',
                'workout_id' => 33, // Zumba
                'q_value' => 0.77,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Obesitas',
                'kondisi_kesehatan' => 'Penyakit Jantung',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 15,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Buruk',
                'workout_id' => 27, // Stretching
                'q_value' => 0.81,
            ],
            [
                'usia' => 'Lansia',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan kurang',
                'kondisi_kesehatan' => 'Hipotensi',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 20,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 28, // Yoga 30 menit
                'q_value' => 0.79,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'Kardio',
                'tujuan_workout' => 'Meningkatkan Kebugaran Kardiovaskular',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Bagus',
                'workout_id' => 12, // Bersepeda 30 menit
                'q_value' => 0.82,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan berlebih',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Dance Fitness',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 40,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Bagus',
                'workout_id' => 34, // Aerobik 45 menit
                'q_value' => 0.78,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Obesitas',
                'kondisi_kesehatan' => 'Obesitas',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Kekuatan',
                'tujuan_workout' => 'Meningkatkan Massa Otot & Kekuatan',
                'durasi_latihan' => 25,
                'kelengkapan_alat' => 'Lengkap',
                'mood' => 'Bagus',
                'workout_id' => 41, // Latihan Beban Komplit
                'q_value' => 0.79,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'HIIT',
                'tujuan_workout' => 'Meningkatkan Kebugaran Kardiovaskular',
                'durasi_latihan' => 25,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Bagus',
                'workout_id' => 36, // Latihan Agility
                'q_value' => 0.83,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan berlebih',
                'kondisi_kesehatan' => 'Diabetes',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Bodyweight Training',
                'tujuan_workout' => 'Menurunkan Berat Badan',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Bagus',
                'workout_id' => 18, // Sit-up 5 set
                'q_value' => 0.78,
            ],
            [
                'usia' => 'Lansia',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Obesitas',
                'kondisi_kesehatan' => 'Hipertensi',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 29, // Power Yoga 30 menit
                'q_value' => 0.76,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan berlebih',
                'kondisi_kesehatan' => 'Cedera',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 20,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 27, // Stretching
                'q_value' => 0.80,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'HIIT',
                'tujuan_workout' => 'Meningkatkan Kebugaran Kardiovaskular',
                'durasi_latihan' => 20,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Bagus',
                'workout_id' => 35, // HIIT 20 menit
                'q_value' => 0.82,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan berlebih',
                'kondisi_kesehatan' => 'Asma',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 28, // Yoga 60 menit
                'q_value' => 0.80,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'Dance Fitness',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Bagus',
                'workout_id' => 33, // Zumba
                'q_value' => 0.84,
            ],
            [
                'usia' => 'Lansia',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan kurang',
                'kondisi_kesehatan' => 'Penyakit Jantung',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Kardio',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 4, // Jalan santai 30 menit
                'q_value' => 0.81,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan berlebih',
                'kondisi_kesehatan' => 'Obesitas',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Kardio',
                'tujuan_workout' => 'Menurunkan Berat Badan',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Bagus',
                'workout_id' => 13, // Bersepeda 60 menit
                'q_value' => 0.78,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Obesitas',
                'kondisi_kesehatan' => 'Obesitas',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Bodyweight Training',
                'tujuan_workout' => 'Menurunkan Berat Badan',
                'durasi_latihan' => 10,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Buruk',
                'workout_id' => 20, // Squat 5 set
                'q_value' => 0.76,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan kurang',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'Kekuatan',
                'tujuan_workout' => 'Meningkatkan Massa Otot & Kekuatan',
                'durasi_latihan' => 20,
                'kelengkapan_alat' => 'Lengkap',
                'mood' => 'Bagus',
                'workout_id' => 40, // Squat (Powerlifting)
                'q_value' => 0.79,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'HIIT',
                'tujuan_workout' => 'Meningkatkan Kebugaran Kardiovaskular',
                'durasi_latihan' => 25,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Bagus',
                'workout_id' => 36, // Latihan Peningkatan Agility
                'q_value' => 0.84,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Obesitas',
                'kondisi_kesehatan' => 'Obesitas',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 30, // Tai Chi
                'q_value' => 0.77,
            ],
            [
                'usia' => 'Lansia',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan kurang',
                'kondisi_kesehatan' => 'Cedera',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 15,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 27, // Stretching
                'q_value' => 0.79,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Obesitas',
                'kondisi_kesehatan' => 'Penyakit Jantung',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Kardio',
                'tujuan_workout' => 'Meningkatkan Kebugaran Kardiovaskular',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 12, // Bersepeda 30 menit
                'q_value' => 0.78,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'Kekuatan',
                'tujuan_workout' => 'Meningkatkan Massa Otot & Kekuatan',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Lengkap',
                'mood' => 'Bagus',
                'workout_id' => 39, // Bench Press
                'q_value' => 0.83,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan kurang',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'Dance Fitness',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 45,
                'kelengkapan_alat' => 'Tidak ada',
                'mood' => 'Bagus',
                'workout_id' => 34, // Aerobik 45 menit
                'q_value' => 0.82,
            ],
            [
                'usia' => 'Lansia',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Hipotensi',
                'tingkat_kebugaran' => 'Rendah',
                'jenis_olahraga_favorit' => 'Fleksibilitas',
                'tujuan_workout' => 'Relaksasi',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 28, // Yoga 60 menit
                'q_value' => 0.80,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan normal',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'HIIT',
                'tujuan_workout' => 'Meningkatkan Kebugaran Kardiovaskular',
                'durasi_latihan' => 30,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Bagus',
                'workout_id' => 37, // Cardio Boxing
                'q_value' => 0.81,
            ],
            [
                'usia' => 'Dewasa',
                'jenis_kelamin' => 'Wanita',
                'kategori_bmi' => 'Obesitas',
                'kondisi_kesehatan' => 'Obesitas',
                'tingkat_kebugaran' => 'Sedang',
                'jenis_olahraga_favorit' => 'Bodyweight Training',
                'tujuan_workout' => 'Menurunkan Berat Badan',
                'durasi_latihan' => 20,
                'kelengkapan_alat' => 'Dasar',
                'mood' => 'Buruk',
                'workout_id' => 41, // Latihan Dumbell
                'q_value' => 0.76,
            ],
            [
                'usia' => 'Muda',
                'jenis_kelamin' => 'Pria',
                'kategori_bmi' => 'Berat badan berlebih',
                'kondisi_kesehatan' => 'Normal',
                'tingkat_kebugaran' => 'Tinggi',
                'jenis_olahraga_favorit' => 'Kekuatan',
                'tujuan_workout' => 'Meningkatkan Massa Otot & Kekuatan',
                'durasi_latihan' => 50,
                'kelengkapan_alat' => 'Lengkap',
                'mood' => 'Bagus',
                'workout_id' => 42, // Latihan Beban Komplit
                'q_value' => 0.85,
            ],

        ];

        foreach ($data as $row) {
            QLearningState::create($row);
        }
    }
}